= Spring Framework on Google Cloud PostgreSQL Sample

This code sample demonstrates how to deploy to CloudFoundry a Spring Boot app which depends on link:../../spring-cloud-gcp-starters/spring-cloud-gcp-starter-sql-postgresql[Spring Framework on Google Cloud PostgreSQL Starter] and tries to connect to a Postgresql instance created using https://github.com/cloudfoundry/cloud-service-broker[Cloud Service Broker] + https://github.com/cloudfoundry/csb-brokerpak-gcp[csb-brokerpak-gcp].

What is described here is a workaround to overcome the fact that Spring Framework on Google Cloud PostgreSQL Starter enforces a very opinionated workflow, which doesn't play well out of the box with csb-brokerpak-gcp.
 
== Setup

1. Navigate to the folder containing this README. Assuming you are at the root of the repo, do: `cd "spring-cloud-gcp-samples/spring-cloud-gcp-sql-postgres-sample"`

2. Build the application JAR by running `../../mvnw clean install`.

3. Create a Postgres instance using csb-brokerpak-gcp: `cf create-service "csb-google-postgres" "small" "my-own-gcp-pg-db"`

4. Inject the `.profile` file inside the JAR we just created by running `jar -uf target/*.jar .profile`. 

5. Modify the content of `manifest.yml` to suit your needs. Possibly, changing the application name, etc. It should work out of the box, though.

6. Deploy the application by running `cf push`.

== Disclaimer

Notice that in `manifest.yml` we are specifying `spring_cloud_gcp_sql_enabled: false`.
This means that we are disabling most of the Spring Framework on Google Cloud PostgreSQL Starter functionality.
This is currently needed if we don't want to modify our Spring application to remove the Spring Framework on Google Cloud PostgreSQL Starter dependecy.
In the future csb-brokerpak-gcp may add better support for Spring Framework on Google Cloud PostgreSQL Starter.

One of the goals of this workaround was to not have to modify the application source code at all.
In fact, it is perfectly possible to inject the `.profile` file into an existing JAR coming from
the now unsupported https://github.com/GoogleCloudPlatform/gcp-service-broker[Open Service Broker for Google Cloud Platform].
